apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi-gp3-mongodb
  labels:
    app: mongodb
    managed-by: terraform
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fsType: ext4
  encrypted: "true"
  # Optional: Specify KMS key if you have a custom one
  # kmsKeyId: "your-kms-key-id"
