apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    app: mongodb
    type: ebs
    managed-by: terraform
    volume-name: mongodb-data-1
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-csi-gp3-mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1b  # Must match your Terraform AZ and worker nodes
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0ccb56926a25e2761
    volumeAttributes:
      # These should match your Terraform configuration
      type: gp3
      iops: "3000"
      throughput: "125"
      encrypted: "true"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: aws-eoc
  labels:
    app: mongodb
    managed-by: terraform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-gp3-mongodb
  volumeName: mongodb-pv  # This forces binding to your specific static PV
  resources:
    requests:
      storage: 3Gi
