name: Setup Terraform and Deploy EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Verify Terraform Installation
        run: terraform --version

  eks_setup:
    runs-on: self-hosted
    needs: setup  # This ensures setup job completes first
    environment: production  # Requires manual approval in GitHub settings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Configure AWS Credentials
        run: |
          # AWS credentials should be set as GitHub Secrets
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./aws_terraform_template_eks
        run: terraform init

      - name: Terraform Plan
        working-directory: ./aws_terraform_template_eks
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./aws_terraform_template_eks
        run: terraform apply -auto-approve