name: Setup Terraform and Deploy EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Also allows manual trigger

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          if command -v terraform &> /dev/null; then
            echo "Terraform is already installed"
            /usr/local/bin/terraform version || terraform version
          else
            echo "Installing Terraform..."
            TERRAFORM_VERSION="1.9.8"
            cd /tmp
            wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            sudo chmod +x /usr/local/bin/terraform
            rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            echo "Terraform installed successfully"
          fi
          /usr/local/bin/terraform version

  # eks_setup:
  #   runs-on: self-hosted
  #   environment: production
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Verify Terraform is Available
  #       run: |
  #         which terraform
  #         /usr/local/bin/terraform version

  #     - name: Terraform Init
  #       working-directory: ./aws-eks-setup
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  #       run: /usr/local/bin/terraform init

  #     - name: Terraform Plan
  #       working-directory: ./aws-eks-setup
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  #       run: /usr/local/bin/terraform plan

  #     - name: Terraform Apply
  #       working-directory: ./aws-eks-setup
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  #       run: /usr/local/bin/terraform apply -auto-approve
        
  #     - name: Configure kubectl
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  #       run: |
  #         # Update kubeconfig for the EKS cluster
  #         aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name devops-cluster
          
  #         # Verify kubectl connection
  #         kubectl get nodes
          
  #         # Display cluster info
  #         kubectl cluster-info

  k8s_namespace_setup:
    runs-on: self-hosted
    needs: setup
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure kubectl for EKS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Update kubeconfig for the EKS cluster
          aws eks --region us-east-1 update-kubeconfig --name devops-cluster
          echo "Kubeconfig updated successfully"

      - name: Verify kubectl connection
        run: |
          # Verify kubectl can connect to the cluster
          kubectl get nodes
          echo "Successfully connected to EKS cluster"

      - name: Create namespace
        run: |
          # Create namespace if it doesn't exist
          if kubectl get namespace aws-eoc &> /dev/null; then
            echo "Namespace 'aws-eoc' already exists"
          else
            kubectl create namespace aws-eoc
            echo "Namespace 'aws-eoc' created successfully"
          fi

      - name: Verify namespace
        run: |
          kubectl get namespace aws-eoc
          echo "Namespace verification complete"