name: Setup Terraform

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          # Download Terraform
          TERRAFORM_VERSION="1.9.8"
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          
          # Unzip and install
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          
          # Clean up
          rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          
          # Verify installation
          terraform --version