name: Setup Terraform and Deploy EKS

on:
  workflow_dispatch:  # Only runs when manually triggered from GitHub UI

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          # Check if terraform is already installed
          if command -v terraform &> /dev/null; then
            echo "Terraform is already installed"
            terraform --version
          else
            echo "Installing Terraform..."
            TERRAFORM_VERSION="1.9.8"
            wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            echo "Terraform installed successfully"
          fi
          
          # Verify installation
          terraform --version

  eks_setup:
    runs-on: self-hosted
    needs: setup
    environment: production  # Requires manual approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./aws_terraform_template_eks
        run: terraform init

      - name: Terraform Plan
        working-directory: ./aws_terraform_template_eks
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./aws_terraform_template_eks
        run: terraform apply -auto-approve